version: 2.1

# Executor that runs tests in the image produced by the build step
executors:
  nf-pipeline:
    docker:
      - image: "$DOCKER_USER/salmonella-seq:$CIRCLE_BRANCH"

  nf-machine:
    machine:
      image: ubuntu-1604:202007-01

# Run tests and store artifacts
jobs:
  # Docker image containing the nextflow pipeline $CIRCLE_BRANCH
  build:
    docker:
      # Circleci base ubuntu image
      - image: &build_img cimg/base:2020.01

    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=$CIRCLE_BRANCH
          docker build -t $DOCKER_USER/salmonella-seq:$TAG -f ./docker/Dockerfile .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push $DOCKER_USER/salmonella-seq:$TAG

  # Docker image containing the nextflow pipeline $CIRCLE_BRANCH
  test_isolates:
    executor: nf-machine

    steps:
      - checkout
      - run:
          no_output_timeout: 30m
          command: |
            docker run -m="7g" "$DOCKER_USER/salmonella-seq:$CIRCLE_BRANCH"  /NextflowSerotypingPipeline/nextflow run NXF_VER=20.01.1 SCE3_pipeline_update.nf

# Orchestrates the validation tests 
workflows:
  validation:
    jobs:
      - build

      - test_isolates:
          requires:
            - build
