version: 2.1

# Executor that runs tests in the image produced by the build step
executors:
  nf-pipeline:
    docker:
      - image: "$DOCKER_USER/salmonella-seq:$CIRCLE_BRANCH"

# Run tests and store artifacts
jobs:
  # Docker image containing the nextflow pipeline $CIRCLE_BRANCH
  build:
    docker:
      # Circleci base ubuntu image
      - image: &build_img cimg/base:2020.01

    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=$CIRCLE_BRANCH
          docker build -t $DOCKER_USER/salmonella-seq:$TAG -f ./docker/Dockerfile .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push $DOCKER_USER/salmonella-seq:$TAG

  # Docker image containing the nextflow pipeline $CIRCLE_BRANCH
  test_isolates:
    executor: nf-pipeline

    steps:
      - checkout
      - run: |
          echo ----BEFORE SOURCE----
          which pip
          
          source ~/.bashrc
          
          echo ----AFTER SOURCE----
          which pip
          echo ----Pipping----
          pip install libxml

          echo ----Running----
          /NextflowSerotypingPipeline/nextflow run SCE3_pipeline_update.nf

# Orchestrates the validation tests 
workflows:
  validation:
    jobs:
      - build

      - test_isolates:
          requires:
            - build
