#!/bin/sh
#
#================================================================
# print_todays_wgs_cluster.sh
#================================================================
#
#% DESCRIPTION
#%    Prints the filepath of the WGS Cluster CSV if it were generated by nextflow today. 

echo /WGS_Results/test_isolates_SummaryTable.csv

#TODAY=`date +%d%b%y`
#echo /WGS_Results/Results_reads_${TODAY}/reads_AssignedWGSCluster_${TODAY}.csv
